import api, { clampPageSize } from '@/services/api/api.ts'

export interface MarkupRangeModel {
  id: number
  rangeStart: number
  rangeEnd: number
  markup: number
}

export interface MarkupGroupModel {
  id: number
  name: string | null
  currencyId: number
  autoGenerated: boolean
  ranges: MarkupRangeModel[]
}

export interface UpsertMarkupRangeModel {
  rangeStart: number
  rangeEnd: number
  markup: number
}

export interface UpsertMarkupGroupModel {
  id?: number
  name?: string | null
  currencyId: number
  ranges: UpsertMarkupRangeModel[]
}

export interface GetMarkupGroupsRequest {
  page: number
  size: number
}

export interface GetMarkupGroupsResponse {
  groups: MarkupGroupModel[]
}

export async function getMarkupGroups(req: GetMarkupGroupsRequest): Promise<GetMarkupGroupsResponse> {
  const resp = await api.get<GetMarkupGroupsResponse>('/pricing/markups', {
    params: {
      page: req.page,
      size: clampPageSize(req.size),
    },
  })
  return resp.data
}

export async function upsertMarkupGroup(group: UpsertMarkupGroupModel): Promise<void> {
  await api.post('/pricing/markups', { group })
}
