<template>
  <div class="markups-page">
    <PageHeader :title="t('markups.title')" :description="t('markups.description')">
      <template #actions>
        <el-button :loading="isLoading" @click="loadGroups">
          {{ t('common.actions.refresh') }}
        </el-button>
        <el-button type="primary" @click="openCreateDrawer">
          {{ t('markups.create') }}
        </el-button>
      </template>
    </PageHeader>

    <main class="markups-content">
      <div class="markups-workspace">
        <section class="markups-list-panel">
          <div class="panel-heading">
            <div>
              <h2>{{ t('markups.groups') }}</h2>
              <p>{{ t('markups.groupsCount', { count: groups.length }) }}</p>
            </div>
          </div>

          <el-table
            v-loading="isLoading"
            :data="groups"
            height="100%"
            highlight-current-row
            :empty-text="t('markups.empty')"
            :row-class-name="markupRowClassName"
            @current-change="selectGroup"
          >
            <el-table-column prop="name" :label="t('common.labels.name')" min-width="190">
              <template #default="{ row }: { row: MarkupGroupModel }">
                <div class="markup-title">
                  <strong>{{ row.name || t('markups.unnamed') }}</strong>
                  <span>{{ currencyLabel(row.currencyId) }}</span>
                </div>
              </template>
            </el-table-column>

            <el-table-column :label="t('common.labels.count')" width="92" align="right">
              <template #default="{ row }: { row: MarkupGroupModel }">
                {{ row.ranges.length }}
              </template>
            </el-table-column>

            <el-table-column label="" width="60" align="right">
              <template #default="{ row }: { row: MarkupGroupModel }">
                <ActionIconButton :label="t('common.actions.edit')" :icon="Edit" @click.stop="openEditDrawer(row)" />
              </template>
            </el-table-column>
          </el-table>

          <div class="markups-footer">
            <ZeroPagination v-model:page="page" v-model:size="limit" :has-next="hasNext" />
          </div>
        </section>

        <section class="markups-details-panel">
          <template v-if="selectedGroup">
            <div class="details-header">
              <div class="markup-title">
                <strong>{{ selectedGroup.name || t('markups.unnamed') }}</strong>
                <span>#{{ selectedGroup.id }} · {{ selectedGroup.autoGenerated ? t('markups.autoGenerated') : t('markups.manual') }}</span>
              </div>
              <ActionIconButton :label="t('common.actions.edit')" :icon="Edit" @click="openEditDrawer(selectedGroup)" />
            </div>

            <div class="details-summary">
              <div>
                <span>{{ t('markups.currency') }}</span>
                <strong>{{ currencyLabel(selectedGroup.currencyId) }}</strong>
              </div>
              <div>
                <span>{{ t('markups.ranges') }}</span>
                <strong>{{ t('markups.rangesCount', { count: selectedGroup.ranges.length }) }}</strong>
              </div>
              <div>
                <span>{{ t('markups.source') }}</span>
                <strong>{{ selectedGroup.autoGenerated ? t('markups.autoGenerated') : t('markups.manual') }}</strong>
              </div>
            </div>

            <el-table
              :data="selectedGroupRanges"
              border
              class="ranges-table"
              :empty-text="t('markups.noRanges')"
            >
              <el-table-column :label="t('markups.range')" min-width="220">
                <template #default="{ row }: { row: MarkupRangeModel }">
                  {{ formatMoney(row.rangeStart, selectedGroup.currencyId) }} - {{ formatMoney(row.rangeEnd, selectedGroup.currencyId) }}
                </template>
              </el-table-column>
              <el-table-column :label="t('markups.from')" min-width="130" align="right">
                <template #default="{ row }: { row: MarkupRangeModel }">
                  {{ formatMoney(row.rangeStart, selectedGroup.currencyId) }}
                </template>
              </el-table-column>
              <el-table-column :label="t('markups.to')" min-width="130" align="right">
                <template #default="{ row }: { row: MarkupRangeModel }">
                  {{ formatMoney(row.rangeEnd, selectedGroup.currencyId) }}
                </template>
              </el-table-column>
              <el-table-column :label="t('markups.markup')" width="140" align="right">
                <template #default="{ row }: { row: MarkupRangeModel }">
                  <strong>{{ formatPercent(row.markup) }}</strong>
                </template>
              </el-table-column>
            </el-table>
          </template>

          <el-empty v-else :description="t('markups.selectToView')" />
        </section>
      </div>
    </main>

    <el-drawer
      v-model="drawerOpen"
      direction="rtl"
      size="min(620px, 100vw)"
      :title="drawerTitle"
      class="markup-drawer"
    >
      <div class="markup-drawer__content">
        <div class="markup-drawer__body">
          <el-form label-position="top" @submit.prevent>
            <section class="markup-form-section">
              <div class="markup-form-section__title">{{ t('markups.groupInfo') }}</div>
              <el-form-item :label="t('common.labels.name')">
                <el-input
                  v-model="form.name"
                  clearable
                  maxlength="128"
                  show-word-limit
                  :placeholder="t('markups.namePlaceholder')"
                />
              </el-form-item>

              <el-form-item :label="t('markups.currency')" required>
                <el-select
                  v-model="form.currencyId"
                  filterable
                  class="w-full"
                  :loading="isLoadingCurrencies"
                  :placeholder="t('markups.currencyPlaceholder')"
                >
                  <el-option
                    v-for="currency in currencies"
                    :key="currency.id"
                    :label="currencyLabel(currency.id)"
                    :value="currency.id"
                  />
                </el-select>
              </el-form-item>
            </section>

            <section class="markup-form-section">
              <div class="markup-ranges-header">
                <div class="markup-form-section__title">{{ t('markups.ranges') }}</div>
                <el-button plain size="small" @click="addRange">
                  {{ t('markups.addRange') }}
                </el-button>
              </div>

              <div class="markup-ranges-editor">
                <div
                  v-for="(range, index) in form.ranges"
                  :key="range.key"
                  class="markup-range-row"
                >
                  <label>
                    <span>{{ t('markups.from') }}</span>
                    <el-input-number v-model="range.rangeStart" :min="0" :controls="false" class="w-full" />
                  </label>
                  <label>
                    <span>{{ t('markups.to') }}</span>
                    <el-input-number v-model="range.rangeEnd" :min="0" :controls="false" class="w-full" />
                  </label>
                  <label>
                    <span>{{ t('markups.markupPercent') }}</span>
                    <el-input-number v-model="range.markupPercent" :min="0" :precision="2" :controls="false" class="w-full" />
                  </label>
                  <ActionIconButton
                    :label="t('common.actions.delete')"
                    :icon="Delete"
                    tone="danger"
                    :disabled="form.ranges.length === 1"
                    @click="removeRange(index)"
                  />
                </div>
              </div>
            </section>
          </el-form>
        </div>

        <div class="markup-drawer__footer">
          <el-button @click="drawerOpen = false">{{ t('common.actions.cancel') }}</el-button>
          <el-button type="primary" :loading="isSaving" @click="saveGroup">
            {{ t('common.actions.save') }}
          </el-button>
        </div>
      </div>
    </el-drawer>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { Delete, Edit } from '@element-plus/icons-vue'
import ActionIconButton from '@/components/common/ActionIconButton.vue'
import PageHeader from '@/components/common/PageHeader.vue'
import ZeroPagination from '@/components/common/ZeroPagination.vue'
import type { CurrencyModel } from '@/models/currencyModel.ts'
import { getCurrencies } from '@/services/api/currencies.ts'
import {
  getMarkupGroups,
  upsertMarkupGroup,
  type MarkupGroupModel,
  type MarkupRangeModel,
} from '@/services/api/markups.ts'
import { useI18n } from '@/i18n'

interface RangeFormRow {
  key: string
  rangeStart: number
  rangeEnd: number
  markupPercent: number
}

const { locale, t } = useI18n()

const groups = ref<MarkupGroupModel[]>([])
const currencies = ref<CurrencyModel[]>([])
const isLoading = ref(false)
const isSaving = ref(false)
const isLoadingCurrencies = ref(false)
const drawerOpen = ref(false)
const editingGroupId = ref<number | null>(null)
const selectedGroupId = ref<number | null>(null)
const page = ref(0)
const limit = ref(20)
const hasNext = ref(false)

const form = reactive<{
  name: string
  currencyId: number | null
  ranges: RangeFormRow[]
}>({
  name: '',
  currencyId: null,
  ranges: [],
})

const drawerTitle = computed(() => editingGroupId.value
  ? t('markups.edit')
  : t('markups.create'))

const currencyById = computed(() => new Map(currencies.value.map((currency) => [currency.id, currency])))
const selectedGroup = computed(() => groups.value.find((group) => group.id === selectedGroupId.value))
const selectedGroupRanges = computed(() => selectedGroup.value ? sortedRanges(selectedGroup.value.ranges) : [])

watch([page, limit], () => {
  loadGroups()
})

onMounted(async () => {
  await Promise.all([
    loadCurrencies(),
    loadGroups(),
  ])
})

async function loadCurrencies() {
  isLoadingCurrencies.value = true
  try {
    const response = await getCurrencies()
    currencies.value = response.currencies
  } catch (error) {
    ElMessage.error(error instanceof Error ? error.message : t('markups.loadCurrenciesError'))
  } finally {
    isLoadingCurrencies.value = false
  }
}

async function loadGroups() {
  isLoading.value = true
  try {
    const response = await getMarkupGroups({
      page: page.value,
      size: limit.value,
    })
    groups.value = response.groups
    hasNext.value = response.groups.length === limit.value
    ensureSelectedGroup()
  } catch (error) {
    ElMessage.error(error instanceof Error ? error.message : t('markups.loadError'))
  } finally {
    isLoading.value = false
  }
}

function openCreateDrawer() {
  editingGroupId.value = null
  form.name = ''
  form.currencyId = currencies.value[0]?.id ?? null
  form.ranges = [createRangeRow()]
  drawerOpen.value = true
}

function openEditDrawer(group: MarkupGroupModel) {
  editingGroupId.value = group.id
  form.name = group.name ?? ''
  form.currencyId = group.currencyId
  form.ranges = sortedRanges(group.ranges).map((range) => ({
    key: crypto.randomUUID(),
    rangeStart: range.rangeStart,
    rangeEnd: range.rangeEnd,
    markupPercent: range.markup * 100,
  }))
  if (form.ranges.length === 0) {
    form.ranges = [createRangeRow()]
  }
  drawerOpen.value = true
}

function addRange() {
  const last = form.ranges[form.ranges.length - 1]
  form.ranges.push(createRangeRow(last?.rangeEnd ?? 0))
}

function removeRange(index: number) {
  if (form.ranges.length === 1) return
  form.ranges.splice(index, 1)
}

function createRangeRow(start = 0): RangeFormRow {
  return {
    key: crypto.randomUUID(),
    rangeStart: start,
    rangeEnd: start + 1,
    markupPercent: 0,
  }
}

async function saveGroup() {
  const validationError = validateForm()
  if (validationError) {
    ElMessage.warning(validationError)
    return
  }

  isSaving.value = true
  try {
    await upsertMarkupGroup({
      id: editingGroupId.value ?? undefined,
      name: form.name.trim() || null,
      currencyId: form.currencyId!,
      ranges: form.ranges.map((range) => ({
        rangeStart: range.rangeStart,
        rangeEnd: range.rangeEnd,
        markup: range.markupPercent / 100,
      })),
    })
    ElMessage.success(t('markups.saved'))
    drawerOpen.value = false
    selectedGroupId.value = editingGroupId.value
    await loadGroups()
  } catch (error) {
    ElMessage.error(error instanceof Error ? error.message : t('markups.saveError'))
  } finally {
    isSaving.value = false
  }
}

function selectGroup(group?: MarkupGroupModel) {
  selectedGroupId.value = group?.id ?? null
}

function ensureSelectedGroup() {
  if (groups.value.length === 0) {
    selectedGroupId.value = null
    return
  }

  if (!selectedGroupId.value || !groups.value.some((group) => group.id === selectedGroupId.value)) {
    selectedGroupId.value = groups.value[0]?.id ?? null
  }
}

function markupRowClassName({ row }: { row: MarkupGroupModel }) {
  return row.id === selectedGroupId.value ? 'markup-row markup-row--selected' : 'markup-row'
}

function validateForm() {
  if (!form.currencyId) return t('markups.currencyRequired')
  if (form.ranges.length === 0) return t('markups.rangesRequired')

  const invalidRangeIndex = form.ranges.findIndex((range) => range.rangeEnd <= range.rangeStart)
  if (invalidRangeIndex >= 0) {
    return t('markups.rangeInvalid', { index: invalidRangeIndex + 1 })
  }

  return ''
}

function sortedRanges(ranges: MarkupRangeModel[]) {
  return [...ranges].sort((a, b) => a.rangeStart - b.rangeStart)
}

function currencyLabel(currencyId: number) {
  const currency = currencyById.value.get(currencyId)
  if (!currency) return `#${currencyId}`
  return `${currency.name} (${currency.currencySign})`
}

function formatMoney(value: number, currencyId: number) {
  const currency = currencyById.value.get(currencyId)
  const amount = new Intl.NumberFormat(locale.value, {
    maximumFractionDigits: 2,
  }).format(value)
  return currency ? `${amount} ${currency.currencySign}` : amount
}

function formatPercent(value: number) {
  return new Intl.NumberFormat(locale.value, {
    style: 'percent',
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(value)
}
</script>

<style scoped>
.markups-page {
  min-height: 100%;
  background: var(--app-bg);
}

.markups-content {
  padding: 24px;
}

.markups-workspace {
  display: grid;
  grid-template-columns: minmax(360px, 0.85fr) minmax(0, 1.15fr);
  gap: 16px;
}

.markups-list-panel,
.markups-details-panel {
  border: 1px solid var(--app-border);
  border-radius: 8px;
  background: var(--app-surface);
}

.markups-list-panel {
  display: grid;
  grid-template-rows: auto minmax(0, 1fr) auto;
  height: 720px;
  overflow: hidden;
}

.markups-details-panel {
  display: flex;
  min-width: 0;
  flex-direction: column;
  gap: 14px;
  padding: 16px;
}

.panel-heading {
  border-bottom: 1px solid var(--app-border);
  padding: 14px 16px;
}

.panel-heading h2 {
  margin: 0;
  color: var(--app-text);
  font-size: 17px;
  font-weight: 700;
}

.panel-heading p {
  margin: 3px 0 0;
  color: var(--app-text-muted);
  font-size: 13px;
}

.markup-title {
  display: flex;
  min-width: 0;
  flex-direction: column;
  gap: 3px;
}

.markup-title strong {
  color: #0f172a;
  font-weight: 650;
}

.markup-title span {
  color: #64748b;
  font-size: 12px;
}

.details-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.details-summary {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 10px;
}

.details-summary > div {
  display: grid;
  gap: 4px;
  border: 1px solid var(--app-border);
  border-radius: 8px;
  background: var(--app-bg-soft);
  padding: 10px 12px;
}

.details-summary span {
  color: var(--app-text-muted);
  font-size: 12px;
  font-weight: 600;
}

.details-summary strong {
  color: var(--app-text);
  font-size: 14px;
}

.ranges-table {
  width: 100%;
}

.markups-footer {
  border-top: 1px solid var(--app-border);
  background: var(--app-surface-tinted);
  padding: 12px 16px;
}

:deep(.markup-row) {
  cursor: pointer;
}

:deep(.markup-row:hover > td) {
  background: #f8fafc !important;
}

:deep(.markup-row--selected > td) {
  background: #ecfdf5 !important;
}

:deep(.markup-drawer .el-drawer__header) {
  margin-bottom: 0;
  border-bottom: 1px solid var(--app-border);
  background: var(--app-surface-tinted);
  padding: 18px 20px;
}

:deep(.markup-drawer .el-drawer__body) {
  padding: 0;
}

.markup-drawer__content {
  display: flex;
  height: 100%;
  flex-direction: column;
}

.markup-drawer__body {
  flex: 1;
  overflow: auto;
  padding: 18px 20px 24px;
}

.markup-drawer__footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
  border-top: 1px solid var(--app-border);
  background: var(--app-surface-tinted);
  padding: 14px 20px;
}

.markup-form-section {
  border: 1px solid var(--app-border);
  border-radius: 8px;
  background: var(--app-surface);
  padding: 14px;
}

.markup-form-section + .markup-form-section {
  margin-top: 14px;
}

.markup-form-section__title {
  margin-bottom: 12px;
  color: #0f172a;
  font-size: 15px;
  font-weight: 650;
}

.markup-ranges-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 12px;
}

.markup-ranges-header .markup-form-section__title {
  margin-bottom: 0;
}

.markup-ranges-editor {
  display: grid;
  gap: 10px;
}

.markup-range-row {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1fr) auto;
  align-items: end;
  gap: 10px;
  border-top: 1px solid var(--app-border);
  padding-top: 10px;
}

.markup-range-row:first-child {
  border-top: 0;
  padding-top: 0;
}

.markup-range-row label {
  display: grid;
  gap: 7px;
  min-width: 0;
}

.markup-range-row label > span {
  color: #334155;
  font-size: 13px;
  font-weight: 650;
}

@media (max-width: 720px) {
  .markups-content {
    padding: 12px;
  }

  .markups-workspace {
    grid-template-columns: 1fr;
  }

  .markups-list-panel {
    height: 520px;
  }

  .details-summary {
    grid-template-columns: 1fr;
  }

  .markup-range-row {
    grid-template-columns: 1fr;
  }
}
</style>
